### PR TITLE
Add a license

### PR DESCRIPTION
**Pull request by ItsPhant**
This is used in a couple of active projects so it would be nice to have one to prevent possible issues.

### CODE REVIEW

**Comment by Lulalaby** [comment]
@TooTallNate ??

**Comment by TooTallNate** [comment]
Sorry, I missed this one. Merging.

**Comment by Lulalaby** [comment]
Thanks ❤️ 
So my checks won't fail anymore ^^

**Comment by Lulalaby** [comment]
@TooTallNate do you add it to the npm registry?

**Pull request merged**
